(unsloth_env) huiyu@huiyu-linux2:~/Workspace/AIAssistant/AIAssistantTraining/mytest$ python3 talk_with_llm.py 
질문을 입력하세요: what is it?
Traceback (most recent call last):
  File "/home/huiyu/Workspace/AIAssistant/AIAssistantTraining/mytest/talk_with_llm.py", line 37, in <module>
    answer = ask_llm(question)
             ^^^^^^^^^^^^^^^^^
  File "/home/huiyu/Workspace/AIAssistant/AIAssistantTraining/mytest/talk_with_llm.py", line 25, in ask_llm
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huiyu/miniconda3/envs/unsloth_env/lib/python3.11/site-packages/openai/_utils/_utils.py", line 287, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/huiyu/miniconda3/envs/unsloth_env/lib/python3.11/site-packages/openai/resources/chat/completions/completions.py", line 1087, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/huiyu/miniconda3/envs/unsloth_env/lib/python3.11/site-packages/openai/_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huiyu/miniconda3/envs/unsloth_env/lib/python3.11/site-packages/openai/_base_client.py", line 1037, in request
    raise self._make_status_error_from_response(err.response) from No
